there is an exception
in finally block
